[package]
name = "yfinance-rust"
version = "0.1.0"
authors = ["Hongze Xia <hongzex@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
clap = "3.0.0-beta.2"